### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by LuisENT** [tonkku107/discord-musicbot#2]
Bot fails to chat.
the error code is here.
        status: 401,
        text: '{"code": 0, "message": "401: Unauthorized"}',
        method: 'GET',
        path: '/api/oauth2/applications/@me' },

I was insert my bot token but not worked.

**Comment by tonkku107** [comment]
What command do you run it with?

**Comment by LuisENT** [comment]
Found this cause.
Note that the token " Bot " is written in a token and is normally authenticated.

Thanks for support.
